import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          disabledBackgroundColor: appTheme.whiteA700,
          backgroundColor: colorScheme.primary,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(4.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: colorScheme.primary,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(4.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: colorScheme.primary,
      ),
      dividerTheme: DividerThemeData(
        thickness: 1,
        space: 1,
        color: appTheme.blueGray800.withOpacity(0.42),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 16.fSize,
          fontFamily: 'Museo Sans Rounded',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: appTheme.blueGray800.withOpacity(0.56),
          fontSize: 14.fSize,
          fontFamily: 'Museo Sans Rounded',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 12.fSize,
          fontFamily: 'Museo Sans Rounded',
          fontWeight: FontWeight.w300,
        ),
        headlineLarge: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 30.fSize,
          fontFamily: 'Museo Sans Rounded',
          fontWeight: FontWeight.w500,
        ),
        titleLarge: TextStyle(
          color: appTheme.blueGray800,
          fontSize: 20.fSize,
          fontFamily: 'Museo Sans Rounded',
          fontWeight: FontWeight.w500,
        ),
        titleMedium: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 16.fSize,
          fontFamily: 'Museo Sans Rounded',
          fontWeight: FontWeight.w500,
        ),
        titleSmall: TextStyle(
          color: appTheme.red500,
          fontSize: 14.fSize,
          fontFamily: 'Colfax',
          fontWeight: FontWeight.w500,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF31A05F),
    primaryContainer: Color(0X0C202020),
    secondary: Color(0X0C202020),
    secondaryContainer: Color(0XFF1C91DA),
    tertiary: Color(0X0C202020),
    tertiaryContainer: Color(0XFF1C91DA),

    // Background colors
    background: Color(0X0C202020),

    // Surface colors
    surface: Color(0X0C202020),
    surfaceTint: Color(0X0C202020),
    surfaceVariant: Color(0XFF1C91DA),

    // Error colors
    error: Color(0X0C202020),
    errorContainer: Color(0XFF1C91DA),
    onError: Color(0XFFFBAC80),
    onErrorContainer: Color(0X0C202020),

    // On colors(text colors)
    onBackground: Color(0XFFFBAC80),
    onInverseSurface: Color(0XFFFBAC80),
    onPrimary: Color(0X0C202020),
    onPrimaryContainer: Color(0XFFFBAC80),
    onSecondary: Color(0XFFFBAC80),
    onSecondaryContainer: Color(0X0C202020),
    onTertiary: Color(0XFFFBAC80),
    onTertiaryContainer: Color(0X0C202020),

    // Other colors
    outline: Color(0X0C202020),
    outlineVariant: Color(0X0C202020),
    scrim: Color(0X0C202020),
    shadow: Color(0X0C202020),

    // Inverse colors
    inversePrimary: Color(0X0C202020),
    inverseSurface: Color(0X0C202020),

    // Pending colors
    onSurface: Color(0XFFFBAC80),
    onSurfaceVariant: Color(0X0C202020),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Black
  Color get black900 => Color(0XFF000000);

  // BlueGray
  Color get blueGray300 => Color(0XFF9CA5BF);
  Color get blueGray400 => Color(0XFF838FAF);
  Color get blueGray40001 => Color(0XFF888888);
  Color get blueGray800 => Color(0XFF243657);
  Color get blueGray900 => Color(0XFF333333);
  Color get blueGray90019 => Color(0X19373636);

  // BlueGraye
  Color get blueGray9007e => Color(0X7E202A43);

  // DeepOrange
  Color get deepOrange500 => Color(0XFFFA6523);
  Color get deepOrangeA20019 => Color(0X19FA7032);

  // DeepPurple
  Color get deepPurple500 => Color(0XFF643BDA);
  Color get deepPurpleA100 => Color(0XFFA278F5);

  // Gray
  Color get gray100 => Color(0XFFF4F5F6);
  Color get gray50 => Color(0XFFFAF9F9);

  // Green
  Color get green900 => Color(0XFF074B23);

  // Red
  Color get red500 => Color(0XFFFF3C3C);

  // Teal
  Color get teal900 => Color(0XFF00411B);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
